### ISSUE TITLE
What if the huggingface dataset has more parameters? E.g., subset

### ISSUE THREAD

**Issue by chunthebear** [amikos-tech/chromadb-data-pipes#139]
I do not think cdp handles additional config parameters, e.g. a subset of a HF dataset. Any help is appreciated!

**Comment by chunthebear** [comment]
Figured out, had to modify the source codes a bit.

**Comment by tazarov** [comment]
the import/export commands have a bunch of params to map features from/to the datasets.

**Comment by chunthebear** [comment]
The config parameter is missing. I added it in my repo: https://github.com/chunthebear/chromadb-data-pipes
