### ISSUE TITLE
Make chromadb package optional dependency

### ISSUE THREAD

**Issue by tazarov** [amikos-tech/chromadb-data-pipes#169]
Make a check on cdp package init if Chroma is present in the venv and if not raise an error

**Comment by tazarov** [comment]
@Krishn1412, sure thing. Thanks for willing to contribute.

Here's the change that I was looking for:


<img width="1181" alt="image" src="https://github.com/user-attachments/assets/84243c02-8025-4d2e-b909-3c3cf6ca1263">

```toml
chromadb = { version = ">=0.4.0,<0.6.0", optional = true }
```

This will allow the package to be installed without doing the chromadb package install itself.

Then in `chroma_dp/__init__.py` file to add this to the top:

```py
try:
    import chromadb  # noqa: F401
except ImportError:
    raise ValueError(
        "The chromadb is not installed. This package (chromadbx) requires that Chroma is installed to work. "
        "Please install it with `pip install chromadb`"
    )
```

The above code will check if Chroma is installed in the current venv and raise an error.

**Comment by Krishn1412** [comment]
thanks for the guidance @tazarov, much appreciated. I have raised a [PR](https://github.com/amikos-tech/chromadb-data-pipes/pull/174) for the issue, can you check this out.
